/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2019-02-28-0fe5c2b519"
#endif /* AVUTIL_FFVERSION_H */
